### ISSUE TITLE
AssemblyTypeResolver fails to discover the "Specify" assembly when running in .NET Core

### ISSUE THREAD

**Issue by shaynevanasperen** [mwhelan/Specify#16]
When running tests in a .NET Core project, the type initializer for `Specify.Host` throws a `System.InvalidOperationException` in the call to `ConfigScannerFactory.SelectScanner()` on [line 29](https://github.com/mwhelan/Specify/blob/master/src/app/Specify/Host.cs#L29). Inside that method, it fails on [line 25](https://github.com/mwhelan/Specify/blob/master/src/app/Specify/Configuration/Scanners/ConfigScannerFactory.cs#L25) with a message of "*Sequence contains no elements*". This is because in `AssemblyTypeResolver` on [line 100](https://github.com/mwhelan/Specify/blob/master/src/app/Specify/lib/AssemblyTypeResolver.cs#L100), the call to `DependencyContext.Default.RuntimeLibraries` fails to find the currently executing library.

The fix for this is simply to explicity add the "Specify" library, since we know for a fact it is there.

**Comment by mwhelan** [comment]
Hi @shaynevanasperen . I'm curious how this is happening, or perhaps it is better to say when is this happening, as all the tests run locally and on the appveyor server?

**Comment by shaynevanasperen** [comment]
Hi @mwhelan. This happens when I create a .NET Core test project (a project targeting netcoreapp1.0) in Visual Studio 2017 with the new MSBuild tooling (.csproj)
