### ISSUE TITLE
is there any exmaple for using ScenarioFor<> with  story

### ISSUE THREAD

**Issue by srivathsah** [mwhelan/Specify#22]
This looks exactly like what I was planning to do, however I am not sure how to use this when it comes to user stories. In one of your issues https://github.com/mwhelan/Specify/issues/13 you have mentioned something like ScenarioFor<MediatorDriver, PersonStory>. Whats the semantics for TStory here

**Comment by mwhelan** [comment]
Hi @srivathsah 

Yes, check out the [ATM sample](https://github.com/mwhelan/Specify/tree/master/src/Samples/Specify.Samples/Specs/ATM). You can see that the [AccountHolderWithdrawsCashStory](https://github.com/mwhelan/Specify/blob/master/src/Samples/Specify.Samples/Specs/ATM/AccountHolderWithdrawsCashStory.cs) story class is a simple class where you set the story metadata in the constructor. Then you reference that class as the second generic parameter class, such as in the [AccountHasSufficientFunds](https://github.com/mwhelan/Specify/blob/master/src/Samples/Specify.Samples/Specs/ATM/AccountHolderWithdrawsCash.cs) scenario.

**Comment by mwhelan** [comment]
There are 2 types of story base classes (or you could create your own). UserStory follows the As a, I want, So that template. The ValueStory uses the In order to, As a, I want template.

**Comment by srivathsah** [comment]
That's great, cheers
