### ISSUE TITLE
Ninjectify :-)

### ISSUE THREAD

**Issue by AlexKeySmith** [mwhelan/Specify#5]
You've been busy ol'sport - nice commits! Hope you had a nice Christmas!

I'm getting some bits of time, I'm looking into the ninject nuget package at the mo if you're happy for me to work on it?

**Comment by AlexKeySmith** [comment]
btw. I'm following your new sassy SpecifyAutofacBootstrapper stuff as a model for the ninject stuff :sunglasses:

**Comment by mwhelan** [comment]
Hey Alex, nice to hear from you! That was actually next on my list but it would be great if you could look at it. I don't use Ninject as much as Autofac and it has fallen a bit behind.

Yes, the Autofac stuff is exactly the model to follow. I hope it all makes sense....? Documentation is next! :-)

Bascially, Specify will look for a configuration scanner for plugins like autofac/ninject. If it finds one it delegates to it to provide an Ioc container specific bootstrapper. This will either be a 'default' one that the plugin provides to build its own container etc. or a user-implemented class that overrides the Ioc specific base class - which is the extension point for the user to add bits into the container if they need to. Sounds a bit muddly all written out but I'm quite happy with it... :-)

I had made a start on the ninject stuff and have published it to a specify-ninject branch (it is branched from develop). There is a new .nuspec file which appveyor  should pick up and use to generate a .nupkg file for deploying to nuget. Hope it provides some help! I had put in a few TODOs that needed addressing. Would love it if you could look at those! :-)
https://github.com/mwhelan/Specify/tree/specify-ninject

Perhaps if you want to ping me (I'm mjmwdev at gmail) we can discuss further.

**Comment by AlexKeySmith** [comment]
Wicked thanks, I've been having an initial play but nothing compiling yet, so your branch will be a great start thanks!

I've got appveyor setup to test the nuget stuff out and it looks like I can create a [local nuget feed](https://docs.nuget.org/create/hosting-your-own-nuget-feeds) so shouldn't clash with nuget.org.

I like your new bootstrapper stuff I've been reading through it, I think I get the gist of it I'll drop you a line if I get stuck :-)

Nice to hear from you to :-) catch you later

**Comment by AlexKeySmith** [comment]
Hi, hope you're well. :-)

Just to give a little update on the ticket:

I spent some time getting up and running as an "on the train" project but some of the autofac principles  are quite different to ninject so I wasn't quite confident that I was getting the lifecycles correct.

However, good news we're moving to autofac as part of our .net core migration as ninject doesn't seem to be making anything public about their support plans. So easy for me :-) But unfortunately I probably won't get any time to do the ninject work :-(

**Comment by mwhelan** [comment]
Hi @AlexKeySmith, great to hear from you! No worries about this ticket. I'm in a similar boat, preferring Autofac for my own development and not quite as sure about Ninject. I think it does all the things it needs to for Specify, chief of which is to provide a child container per test. My plan is just to add adapters as needed and there is no immediate need for Ninject. With .Net Core around the corner it seems prudent to wait for that anyway.
